# Credit Risk Analysis: Predicting Default Patterns

## Project Overview

This project builds machine learning models to predict whether a credit card customer will default on their next payment.

The analysis uses historical customer financial and repayment data to identify high-risk customers and evaluate predictive model performance.

### Workflow:
- Load cleaned credit risk dataset
- Feature selection and target definition
- Train-test split
- Feature scaling
- Model training and evaluation
- Performance comparison and business interpretation

**Dataset:** Credit Card Default Dataset  
**Records:** 30,000 customers  
**Features:** 25 variables  
**Target Variable:** `default payment next month`

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [2]:
df = pd.read_csv("credit_risk_analysis_EDA.csv")
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month,AGE_BIN,CREDIT_GROUP
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,689,0,0,0,0,1,21-29,<50K
1,2,120000,2,2,2,26,-1,2,0,0,...,3261,0,1000,1000,1000,0,2000,1,21-29,100K-200K
2,3,90000,2,2,2,34,0,0,0,0,...,15549,1518,1500,1000,1000,1000,5000,0,30-39,50K-100K
3,4,50000,2,2,1,37,0,0,0,0,...,29547,2000,2019,1200,1100,1069,1000,0,30-39,<50K
4,5,50000,1,2,1,57,-1,0,-1,0,...,19131,2000,36681,10000,9000,689,679,0,50+,<50K

## Drop Unnecessary Column
Dropped because it's only for EDA.

In [3]:
df = df.drop(["AGE_BIN", "CREDIT_GROUP"], axis=1)

In [4]:
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

## Feature and target selection
X for feature and target selection and y for target label.

In [5]:
X = df.drop("default payment next month", axis=1)
y = df["default payment next month"]

## Train test split
80% training and 20% testing.
Model learns on 80%. Then tested on unseen 20%.

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

## Scaling

In [7]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Testing Models
After train and test split and scaling, test on different models to compare then choose which is the best model.

## Logistic Regression

In [8]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

## Evaluate Logistic Regression
Overall correct predictions.

In [9]:
print("Accuracy:", accuracy_score(y_test, lr_pred))
print(confusion_matrix(y_test, lr_pred))
print(classification_report(y_test, lr_pred))

Accuracy: 0.8076088770231937
[[4547  126]
 [1027  293]]
              precision    recall  f1-score   support

           0       0.82      0.97      0.89      4673
           1       0.70      0.22      0.34      1320

    accuracy                           0.81      5993
   macro avg       0.76      0.60      0.61      5993
weighted avg       0.79      0.81      0.77      5993

## KNN model

In [10]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

knn_pred = knn.predict(X_test)

## Evaluate KNN model
KNN predicts based on nearest similar customers.

In [11]:
print("Accuracy:", accuracy_score(y_test, knn_pred))
print(classification_report(y_test, knn_pred))

Accuracy: 0.7935925246120474
              precision    recall  f1-score   support

           0       0.83      0.92      0.87      4673
           1       0.55      0.33      0.41      1320

    accuracy                           0.79      5993
   macro avg       0.69      0.63      0.64      5993
weighted avg       0.77      0.79      0.77      5993

## Random Forest

In [12]:
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

## Evaluate Random Rorest

In [13]:
print("Accuracy:", accuracy_score(y_test, rf_pred))
print(classification_report(y_test, rf_pred))

Accuracy: 0.8156182212581344
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      4673
           1       0.65      0.35      0.45      1320

    accuracy                           0.82      5993
   macro avg       0.75      0.65      0.67      5993
weighted avg       0.80      0.82      0.79      5993

## Compare models
Best model = highest performance.

In [14]:
models = {
    "Logistic Regression": accuracy_score(y_test, lr_pred),
    "KNN": accuracy_score(y_test, knn_pred),
    "Random Forest": accuracy_score(y_test, rf_pred)
}

pd.DataFrame(models.items(), columns=["Model", "Accuracy"])

                 Model  Accuracy
0  Logistic Regression  0.807609
1                  KNN  0.793593
2        Random Forest  0.815618

But we shouldn't only look at accuracy. Also inspect recall.

## Conclusion

Random Forest achieved the best predictive performance for customer default prediction.

Key predictors observed during EDA:
- repayment delays
- lower credit limits
- customer age
- payment history

This model may help banks identify high-risk customers earlier.